#%RAML 1.0 NamedExample
User:
  [
    {
      id: 1,
      name: "Mario",
      surname: "Rossi",
      email: "mariorossi@test.test",
      address: "Via Mario 1, Roma"
    },
    {
      id: 2,
      name: "Maria",
      surname: "Rossi",
      email: "mariarossi@test.test",
      address: "Via Maria 1, Roma"
    }
  ]